import "dotenv/config";

import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { TavilySearch } from "@langchain/tavily";
import { createReactAgent } from "@langchain/langgraph/prebuilt";

const model = new ChatGoogleGenerativeAI({
    model: "gemini-2.5-flash",
    apiKey: process.env.GOOGLE_API_KEY
});

const search = new TavilySearch({
    apiKey: process.env.TAVILY_API_KEY
});

// ----- 4️⃣Tool - Created by LangGraph  ----
// The tool message contains information retrieved from a tool, allowing the agent to incorporate external data or perform specific actions based on the user's query.
// tool messages are created automatically by the ReAct agent when the model decides to call a tool (Tavily in your case). You do not create them yourself.
// When agent.invoke() runs, LangGraph may insert a ToolMessage into result.messages.
const agent = createReactAgent({
    llm: model,
    tools: [search]
});

async function run() {

    // ----- 1️⃣ SYSTEM - Created by you -----
    // The system message provides context and instructions to the agent, allowing it to understand its role and generate appropriate responses.
    const systemMessage = {
        role: "system",
        content: "You are a Senior AI Research Assistant."
    };

    // ----- 2️⃣ USER - Created by the user ----
    // The user message contains the query or request from the user, which the agent will process and respond to.
    const userMessage = {
        role: "user",
        content: "What is the latest Angular version?"
    };

    try {

        const result = await agent.invoke({
            messages: [
                systemMessage,
                userMessage
            ]
        });

        console.log("\n====== Complete Conversation ======\n");

        result.messages.forEach((m, index) => {

            console.log(`Message ${index + 1}`);

            // prints LangChain’s internal message type (human, ai, tool, system) rather than the raw API role.
            console.log("Role :", m.getType?.() ?? m.role);

            // LangChain message type
            console.log("Type:", m.getType());

            // Tool-specific fields
            if (m.getType() === "tool") {
                console.log("Tool name:", m.name);
                console.log("Tool call id:", m.tool_call_id);
            }

            console.log("Content :", m.content);

            console.log("--------------------------------");

        });

        // ----- 3️⃣ASSISTANT - Created by Gemini ----
        // The assistant message contains the response generated by the agent based on the user's query and the context provided by the system message.
        console.log("\nAssistant Final Response\n");

        console.log(result.messages.at(-1).content);

    } catch (err) {

        // ----- 6️⃣ERROR - Not sent to Gemini. Created by your Node.js application ----
        // The error message contains information about any errors that occurred during the processing of the user's query, allowing for debugging and error handling.
        const errorMessage = {
            role: "error",
            content: err.message
        };

        console.log(errorMessage);

    }

    // ----- 5️⃣FUNCTION (Legacy Example) - Not used anymore in most modern agent frameworks. ----
    // The function message contains information returned from a function call, allowing the agent to incorporate external data or perform specific actions based on the user's query.
    const functionMessage = {
        role: "function",
        name: "getWeather",
        content: JSON.stringify({
            city: "London",
            temperature: 21
        })
    };

    console.log("\nLegacy Function Message");

    console.log(functionMessage);

}

run();